### ISSUE TITLE
RandomAffine is not equivalent to ShiftScaleRotate

### ISSUE THREAD

**Issue by MortenHannemose** [albumentations-team/albumentations#719] opened 2020-10-08 16:31 UTC
Under the "Albumentations equivalents for torchvision transforms" it is stated that ShiftScaleRotate does the same as RandomAffine from torchvision. However, ShiftScaleRotate does not contain any shearing, and is therefore a less flexible augmentation.

**Comment by wanburana** [comment] 2021-07-27 12:02
Upvoted. I was looking for a shearing option too,

**Comment by Dipet** [comment] 2021-07-27 12:11
Have you tried [Affine](https://albumentations.ai/docs/api_reference/augmentations/geometric/transforms/#albumentations.augmentations.geometric.transforms.Affine) transform?

**Comment by wanburana** [comment] 2021-07-27 12:43
> Have you tried [Affine](https://albumentations.ai/docs/api_reference/augmentations/geometric/transforms/#albumentations.augmentations.geometric.transforms.Affine) transform?

yes thank you, I just tried A.Affine and it worked perfectly, At first I thought it is not for normal images because of the geometric class and inavailibility on Demo page. I think this issue should be closed now?

**Comment by Dipet** [comment] 2021-07-27 12:57
Yes, we just forgot to close this issue. 
Our [Affine](https://albumentations.ai/docs/api_reference/augmentations/geometric/transforms/#albumentations.augmentations.geometric.transforms.Affine) transform provides the same functionality.
If you think this is not true, please give a reproducible example.

**Closed by Dipet** 2021-07-27 12:57 UTC
Labels: enhancement

**Comment by wanburana** [comment] 2021-07-27 13:05
> Yes, we just forgot to close this issue.
> Our [Affine](https://albumentations.ai/docs/api_reference/augmentations/geometric/transforms/#albumentations.augmentations.geometric.transforms.Affine) transform provides the same functionality.
> If you think this is not true, please give a reproducible example.

it worked perfectly, thank!

**Comment by MortenHannemose** [comment] 2021-07-27 16:30
[The documentation](https://albumentations.ai/docs/examples/migrating_from_torchvision_to_albumentations/) still refers to `ScaleShiftRotate`, which is what prompted my original question. Should this be opened as a new issue on the documentation Github?
