### ISSUE TITLE
TypeError: image must be numpy array type

### ISSUE THREAD

**Issue by talhaanwarch** [albumentations-team/albumentations#931] opened 2021-06-23 14:56 UTC
albumentation version: 1.0.0  
torch version: 1.9.0+cu102

code
**Data loader**
```

class DataReader(Dataset):
  def __init__(self,df,transform=None):
    super(DataReader,self).__init__()
    self.df=df
    self.transform=transform

  def __len__(self):
    return len(self.df)

  def __getitem__(self,index):
    image_path=self.df.image[index]
    image_label=self.df.label[index]

    #read data
    image = dicom.dcmread(image_path).pixel_array
    image=(x-x.min())/(x.max()-x.min())

    if self.transform:
      image=self.transform(image=image)['image']
    return np.asarray(image),image_label
```
**Augmentation function**
```
def aug():
    """albumentations image augmentation"""
    return Compose([
            Resize(224, 224),
            HorizontalFlip(p=0.5),
            VerticalFlip(p=0.5),
            ShiftScaleRotate(0.05,0.05,5), 
            OpticalDistortion(),
            Cutout(p=0.5),
            ToTensorV2(p=1.0),
        ], p=
1.)
```
**testing it**
```
batch=next(iter(DataLoader(DataReader(train_df,aug()), batch_size = 8, num_workers=1,shuffle=True)))
print(batch[0][0].shape)
grid_img=torchvision.utils.make_grid(batch[0],4,4)
plt.imshow(grid_img.permute(1, 2, 0))
```
Every thing work well till here.
**Model initialize**
```
x=torch.randn(3,1,224,224)
model=densenet121()
model(x)
```
run above test code again and got following error

```
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "<ipython-input-41-a0a6888cb06e>", line 21, in __getitem__
    image=self.transform(image=image)['image']
  File "/usr/local/lib/python3.7/dist-packages/albumentations/core/composition.py", line 166, in __call__
    self._check_args(**data)
  File "/usr/local/lib/python3.7/dist-packages/albumentations/core/composition.py", line 237, in _check_args
    raise TypeError("{} must be numpy array type".format(data_name))
TypeError: image must be numpy array type
```

**Comment by BloodAxe** [comment] 2021-06-23 19:37
Can you print type of image after you loaded it from the dicom?
```
image=(x-x.min())/(x.max()-x.min())
print(type(image), isinstance(image, np.ndarray))
```

**Comment by talhaanwarch** [comment] 2021-06-23 20:06
@BloodAxe when I run it for the first time, I got `<class 'numpy.ndarray'> True`, but after I initialized my model and run it again as said above I got `<class 'torch.Tensor'> False`

**Comment by BloodAxe** [comment] 2021-06-30 17:23
According to stack trace, it seems you're running the code in the notebook, so there is a big change you mess somehow with variable names, or executed cells out-of-order. I could not reproduce your issue, therefore closing as non-reproducible. If the problem persist, please attach self-container code snippet that triggers this error.

**Closed by BloodAxe** 2021-06-30 17:23 UTC

**Comment by talhaanwarch** [comment] 2021-07-06 16:07
@BloodAxe  please check gist
https://colab.research.google.com/gist/talhaanwarch/814bf3acde0396c692189834a625d283/coivd-tpu.ipynb?authuser=3
