### ISSUE TITLE
Irreproducibility of albumentations.Perspective()

### ISSUE THREAD

**Issue by enaskopelja** [albumentations-team/albumentations#1000] opened 2021-08-31 11:22 UTC
## 🐛 Bug

Setting `random.seed()` (as instructed [here](https://albumentations.ai/docs/examples/example_keypoints/#An-example-of-complex-augmentation-pipeline) and [here](https://github.com/albumentations-team/albumentations/issues/93)) does not ensure reproducibility for `albumentations.Perspective()`

## To Reproduce

1. Run the code below twice:
```
import os
import random

import albumentations as A
import cv2
import matplotlib.pyplot as plt
import numpy as np

random.seed(123)

perspective = A.Compose([
    A.Perspective(
        pad_mode=cv2.BORDER_CONSTANT,
        fit_output=True,
        always_apply=True
    )
], keypoint_params=A.KeypointParams(format='xy')
)


def apply(
        image: np.ndarray,
        keypoints: np.ndarray,
):
    augmented = perspective(
        image=image,
        keypoints=keypoints
    )

    return augmented['image'], augmented['keypoints']


if __name__ == '__main__':
    image = np.ones((126, 224, 3))
    keypoints = np.array(
        [
            [11, 8],
            [14, 115],
            [196, 114],
            [201, 13]
        ]
    )
    augmented_image, augmented_keypoints = apply(
        image=image,
        keypoints=keypoints
    )
    
    plt.imshow(augmented_image)
    plt.scatter(*zip(*augmented_keypoints))
    plt.show()

```

## Expected behavior

The same output for both runs

## Environment

 - Albumentations version: `1.0.3`
 - Python version: `3.9.6`
 - OS (e.g., Linux): `macOS Big Sur 11.4`
 - How you installed albumentations: `pip`

**Comment by Dipet** [comment] 2021-08-31 12:21
It is because `Perspective` uses `np.random`. This behaviur will be changed in the future.
At this time, you must also set `np.random.seed(seed)` for reproducibility.

**Comment by Dipet** [comment] 2021-08-31 12:22
This is duplicate of #1001

**Comment by enaskopelja** [comment] 2021-08-31 12:51
The two issues are *not* duplicates, please note the distortion issue in #1001.

**Comment by Dipet** [comment] 2021-08-31 12:54
My fault, I'm sorry.

**Closed** 2021-08-31 13:26 UTC
Labels: bug
