### ISSUE TITLE
GaussNoise broken in 1.4.9

### ISSUE THREAD

**Issue by voegtlel** [albumentations-team/albumentations#1797] opened 2024-06-19 09:30 UTC
## Describe the bug

`GaussNoise` does not give the same results in 1.4.9 as in 1.4.8.

### To Reproduce

```py
import cv2
import albumentations as A
import numpy as np


# Generate an image using numpy which is a simple color gradient
image = np.zeros((128, 128, 3), dtype=np.uint8)
image[:, :, 0] = np.arange(0, 128)[:, None]
image[:, :, 1] = np.arange(0, 128)[None, :]
image[:, :, 2] = 128

# Save the augmented image
cv2.imwrite("albu_raw_img.png", image)

# Define the augmentation pipeline
transform = A.Compose([
    A.GaussNoise(p=1),
])

# Apply the transformation
augmented = transform(image=image)

# Get the augmented image
augmented_image = augmented["image"]

# Save the augmented image
cv2.imwrite("albu_aug1.png", augmented_image)
```

### Expected behavior

I guess this is clear? :D It should be the same.

### Actual behavior

GaussianNoise completely noises the image

### Screenshots

The input:
![image](https://github.com/albumentations-team/albumentations/assets/5764745/c01167a2-d39f-4607-97f3-e3d279c57a39)

Output with 1.4.9:
![image](https://github.com/albumentations-team/albumentations/assets/5764745/b138323a-4c1b-42fc-9093-0ec9fb9a24f8)

Output with 1.4.8:
![image](https://github.com/albumentations-team/albumentations/assets/5764745/905806bd-3025-4310-8a27-f387061104ff)

**Comment by voegtlel** [comment] 2024-06-19 14:04
@JulianJvn thanks for this finding! I also checked the release notes and didn't find this. Absolutely agree, semver should be used and reflect that breaking change.

**Comment by ternaus** [comment] 2024-06-19 16:54
> We ran into the same issue, and it broke our CI.
> 
> * I think `GaussNoise` is not broken as stated in the PR title, but [an additional parameter was introduced](https://github.com/albumentations-team/albumentations/releases/tag/1.4.9) with a default value that changes the behavior. Looking at the [code](https://github.com/albumentations-team/albumentations/blob/ec8cb707d1/albumentations/augmentations/transforms.py#L1660-L1674), you should be able to get the previous behavior by setting `noise_scale_factor=1.0`.
> * The [release notes](https://github.com/albumentations-team/albumentations/releases/tag/1.4.9) do not mention that the default behavior changed (not even how the new parameter is called). Why?
> * Can Albumentations switch to [semantic versioning](https://semver.org)? Changing the default behavior is a breaking change which would merit a major version release under semantic versioning, not a patch version release.

It is possible, but will require extra effort and attention.

Would you consider becoming a sponsor? 

https://github.com/sponsors/albumentations-team

**Comment by daitakahashi** [comment] 2024-06-19 17:15
In my observation, negative noise-values of the GaussNoise are truncated.

```python3
import numpy as np
import albumentations as A
x = np.full((10, 10), 128, dtype=np.uint8)
tr = A.Compose([A.GaussNoise(p=1)])  # for 1.4.8
tr = A.Compose([A.GaussNoise(p=1, noise_scale_factor=1.0)]  # for 1.4.9
```

1.4.8
```
(tr(image=x)['image'] >= x).all()  # -> almost always False
```

1.4.9
```
(tr(image=x)['image'] >= x).all()  # -> always True
```

**Comment by ternaus** [comment] 2024-06-19 17:17
@daitakahashi thank you. Will look at it asap.

**Comment by ternaus** [comment] 2024-06-19 17:25
Made `scale_factor=1` as default in https://github.com/albumentations-team/albumentations/pull/1800

**Comment by daitakahashi** [comment] 2024-06-19 17:27
Here may be the cause. The value `gauss` should be a float array (with negative values).
https://github.com/albumentations-team/albumentations/blob/ec8cb707d16f457cd206db4dc46688f5a4813318/albumentations/augmentations/transforms.py#L1676

```
>>> tr.transforms[0].get_params_dependent_on_targets({'image':x})
{'gauss': array([[253,  11, 253,   3, 255,   2, 252, 253, 251, 254],
       [251, 251, 249, 253, 255,   1,   0,   5, 252,   3],
       [255,   1,   3,   9,   6, 249,   0,   1, 254,  11],
       [251,   2,   0,   1, 249, 253, 252,   0,   0,   5],
       [241,   4,   7,   1, 248, 244,   5,   0, 247,   0],
       [  0, 255, 253,  13,   5,   1,   3, 252, 249,   1],
       [252,   5,   0,   0,   0, 246, 240,   4, 253,   2],
       [  3,   5, 253,   7,   2, 251,   2, 252, 255, 250],
       [  0,   2, 253,  16,   2,   5,   3,   3,   4,   9],
       [  0, 254,   5,  17, 249, 254,  12, 255,   7,   8]], dtype=uint8)}
```

**Comment by ternaus** [comment] 2024-06-19 17:29
Yep, it is this casting.

**Comment by ternaus** [comment] 2024-06-19 19:22
Fixed in https://github.com/albumentations-team/albumentations/pull/1801


@voegtlel @daitakahashi @JulianJvn 

Could you please verify that things work as expected? Default behavior is generate per pixel and noise is not truncated.

If no other issues will come up with it, I will make a hotfix release `1.4.10` in couple hours.

**Comment by voegtlel** [comment] 2024-06-19 20:58
Sorry, won't be able to test this until next Monday, OOO until then. Maybe the others can confirm. Anyways, thanks for the quick fix! 🥳

**Comment by ternaus** [comment] 2024-06-19 22:17
Version 1.4.10 with fix for GaussNoise released.

Thanks @voegtlel @JulianJvn and @daitakahashi for help.

**Closed by ternaus** 2024-06-19 22:17 UTC
Labels: bug
