### ISSUE TITLE
How to use Affine `fit_output` parameter?

### ISSUE THREAD

**Issue by ddfabbro** [albumentations-team/albumentations#1154] opened 2022-04-14 14:42 UTC
I want to produce rotated augmentations without that artificial black corners added after applying rotations. I.e. also find the corresponding scale parameter that "zooms in" on the new image.

Looking at the documentation, `fit_output=True` seems to do exactly what I want

```
fit_output (bool): Whether to modify the affine transformation so that the whole output image is always
            contained in the image plane (``True``) or accept parts of the image being outside
            the image plane (``False``). This can be thought of as first applying the affine transformation
            and then applying a second transformation to "zoom in" on the new image so that it fits the image plane,
            This is useful to avoid corners of the image being outside of the image plane after applying rotations.
            It will however negate translation and scaling.
```

However, when I use it, I can still see the black corners.

```
import numpy as np
from PIL import Image
import albumentations as A

src = "Adrian_Murrell_0001.jpg"
dst = "Adrian_Murrell_0001_rotate.jpg"

transform = A.Compose([ 
    A.Affine(rotate=(-5,5), fit_output=True, always_apply=True)
])

img = np.uint8(Image.open(src))
augmented = transform(image=img)
augmented_image = augmented["image"]
Image.fromarray(augmented_image).save(dst)
```

### Adrian_Murrell_0001.jpg
![Adrian_Murrell_0001](https://user-images.githubusercontent.com/17279638/163413976-1f86e5bb-0d86-4a82-9333-964db1e3cde1.jpg)

### Adrian_Murrell_0001_rotate.jpg
![Adrian_Murrell_0001_rotate](https://user-images.githubusercontent.com/17279638/163414082-9dc3a66d-177f-41a5-ac55-291456ecabbc.jpg)

**Comment by mys007** [comment] 2022-04-20 12:11
Hi, I think this cannot be done with `Affine`. `fit_output=True` enlarges the output image so that not a single pixel of the original image is lost (here, I find the current docs a bit confusing, see https://github.com/albumentations-team/albumentations/pull/1159/commits). But I understand you want to crop it so that no filling pixel is visible. Then, your issue seems to be a duplicate of https://github.com/albumentations-team/albumentations/issues/266.

**Closed** 2022-04-24 05:09 UTC
