### ISSUE TITLE
AttributeError: module 'albumentations' has no attribute 'ColorJitter'

### ISSUE THREAD

**Issue by mojtaba-nafez** [albumentations-team/albumentations#1180] opened 2022-06-07 08:04 UTC
import albumentations as A
train_transforms = A.Compose(
    [
        A.LongestMaxSize(max_size=int(IMAGE_SIZE * scale)),
        A.PadIfNeeded(
            min_height=int(IMAGE_SIZE * scale),
            min_width=int(IMAGE_SIZE * scale),
            border_mode=cv2.BORDER_CONSTANT,
        ),
        A.RandomCrop(width=IMAGE_SIZE, height=IMAGE_SIZE),
        A.ColorJitter(brightness=0.6, contrast=0.6, saturation=0.6, hue=0.6, p=0.4),
        A.OneOf(
            [
                A.ShiftScaleRotate(
                    rotate_limit=20, p=0.5, border_mode=cv2.BORDER_CONSTANT
                ),
                A.IAAAffine(shear=15, p=0.5, mode="constant"),
            ],
            p=1.0,
        ),
        A.HorizontalFlip(p=0.5),
        A.Blur(p=0.1),
        A.CLAHE(p=0.1),
        A.Posterize(p=0.1),
        A.ToGray(p=0.1),
        A.ChannelShuffle(p=0.05),
        A.Normalize(mean=[0, 0, 0], std=[1, 1, 1], max_pixel_value=255,),
        ToTensorV2(),
    ],
    bbox_params=A.BboxParams(format="yolo", min_visibility=0.4, label_fields=[],),
)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-8-e3c78bbacb72>](https://localhost:8080/#) in <module>()
     44         ),
     45         A.RandomCrop(width=IMAGE_SIZE, height=IMAGE_SIZE),
---> 46         A.ColorJitter(brightness=0.6, contrast=0.6, saturation=0.6, hue=0.6, p=0.4),
     47         A.OneOf(
     48             [

AttributeError: module 'albumentations' has no attribute 'ColorJitter'

**Comment by zakajd** [comment] 2022-06-22 22:22
What library version did you use? 
Post output of `import albumentations; print(albumentations.__version__)`
Tried to replicate this issue on 1.1.0 and everything worked fine (except that `A.IAAAffine` is marked as deprecated now). 

```python
import albumentations as A
IMAGE_SIZE = 512
train_transforms = A.Compose([
    A.LongestMaxSize(max_size=int(IMAGE_SIZE * scale)),
    A.PadIfNeeded(
        min_height=int(IMAGE_SIZE * scale),
        min_width=int(IMAGE_SIZE * scale),
        border_mode=cv2.BORDER_CONSTANT,
    ),
    A.RandomCrop(width=IMAGE_SIZE, height=IMAGE_SIZE),
    A.ColorJitter(brightness=0.6, contrast=0.6, saturation=0.6, hue=0.6, p=0.4),
    A.OneOf([
        A.ShiftScaleRotate(rotate_limit=20, p=0.5, border_mode=cv2.BORDER_CONSTANT),
        A.Affine(shear=15, p=0.5, mode="constant"),
    ], p=1.0,),
    A.HorizontalFlip(p=0.5),
    A.Blur(p=0.1),
    A.CLAHE(p=0.1),
    A.Posterize(p=0.1),
    A.ToGray(p=0.1),
    A.ChannelShuffle(p=0.05),
    A.Normalize(mean=[0, 0, 0], std=[1, 1, 1], max_pixel_value=255,),
    ToTensorV2(),
    ],
    bbox_params=A.BboxParams(format="yolo", min_visibility=0.4, label_fields=[],),
)
```

**Comment by ternaus** [comment] 2024-04-08 20:34
Could not reproduce as of version `1.4.2`

**Closed by ternaus** 2024-04-08 20:34 UTC
Labels: Need more info
