### ISSUE TITLE
The memory size increases when applying GaussNoise in ReplayCompose

### ISSUE THREAD

**Issue by rose-jinyang** [albumentations-team/albumentations#1077] opened 2021-12-09 07:30 UTC
Hello
How are you?
Thanks for contributing to this project.
The memory size increases when applying GaussNoise transformation to an image repeatedly.

img = cv2.imread('image.jpg')
transformation = A.ReplayCompose( [A.GaussNoise(var_limit=(10.0, 50.0), mean=0, always_apply=False, p=0.5)])

tr = []
for i in range(100):
    data = transformation(image=img)
    tr.append(data['replay']

Please check the above code example and then u can see the memory increasing

**Comment by Dipet** [comment] 2021-12-09 08:57
- Of course, it will be increased because you collect all new images into `tr` list. What kind of behavior do you expect?

**Comment by rose-jinyang** [comment] 2021-12-09 10:38
What is collected into the tr list is NOT image data. It is a small dictionary containing augmentation parameters.

**Comment by rose-jinyang** [comment] 2021-12-09 10:42
What is strange, this issue does not appear when using ISONoise rather than GaussNoise.

**Comment by Dipet** [comment] 2021-12-09 12:54
It is because for replay we save noise, that will be added to the image and it is has the same shape as image
For ISONoise we just save hyper parameters to reproduce the noise.
It is not a bug.
To save memory better to save just hyper parameters, for augmentation speed better to save generated noise, because it is could be applied to multiple images.

**Comment by rose-jinyang** [comment] 2021-12-09 14:18
Thanks for your quick apply.

**Closed** 2021-12-09 14:21 UTC
